# Generated by Django 3.2.9 on 2021-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0002_auto_20211122_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_data',
            field=models.TextField(verbose_name='tweet message'),
        ),
    ]
